# config/validator/MeteoData.yaml

App\Entity\MeteoData:
  properties:
    date:
      - NotBlank: ~
    location:
      - NotBlank: ~
    celsius_temperature:
      - NotBlank: ~
      - Range:
          min: -80
          max: 80
    flcelsius_temperature:
      - NotBlank: ~
      - Range:
          min: -80
          max: 80
    pressure:
      - Range:
          min: 900
          max: 1200
          notInRangeMessage: 'Pressure must be between 900 and 1200.'
    humidity:
      - Range:
          min: 0
          max: 100
          notInRangeMessage: 'Humidity must be between 0 and 100 %.'
    wind_speed:
      - Range:
          min: 0
          max: 80
    cloudiness:
      - Range:
          min: 0
          max: 100
          notInRangeMessage: 'Cloudiness must be between 0 and 100 %.'

